---
title: "Data Manipulation"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
```

## Import some data

I want to import 'FAS_litters.csv'

```{r}
litter_df <- read_csv("data/FAS_litters.csv")
litter_df = janitor::clean_names(litter_df)

pups_df <- read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## 'select'

Let's select some columns

```{r}
select(litter_df, group, litter_number)
select(litter_df, group, gd0_weight, gd18_weight)
select(litter_df, group, starts_with("pups"))

select(litter_df, group, gd0_weight:gd_of_birth)
select(litter_df, -litter_number)

select(litter_df, GROUP = group, litter_number)
rename(litter_df, GROUP = group)

select(litter_df, litter_number, everything())

relocate(litter_df, litter_number)

select(pups_df, litter_number, sex, pd_ears)


```

## ‘filter'

```{r}
filter(litter_df, gd_of_birth == 20)
filter(litter_df, group == "Con7")

filter(litter_df, gd0_weight < 23)

filter(litter_df, pups_survive != 4)

filter(litter_df, !(group == "Con7"))
filter(litter_df, group %in% c("Con7", "Con8"))
filter(litter_df, group == "Con7", gd_of_birth == 20)

drop_na(litter_df)
drop_na(litter_df, gd0_weight)
```

## 'mutate'

Let's add or change column!
```{r}
mutate(litter_df,
       weigh_change = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

## 'arrange'

Let's rearrange the data.
```{r}
arrange(litter_df, gd0_weight)
arrange(litter_df, desc(gd0_weight))

```













