---
title: "Simple document"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Import some data

I want to import 'FAS_litters.csv'

```{r}
litter_df <- read_csv("data/FAS_litters.csv")
```

Yap! I imported this dataset Now I want better names.

```{r}
names(litter_df)

litter_df = janitor::clean_names(litter_df)
```

Now we have better names. Let's look at the dataset.

```{r}
litter_df

head(litter_df)
tail(litter_df)
```

One I use a lot is:

```{r, echo=FALSE}
view(litter_df)
```
 
here is 'skimr':
```{r}
skimr::skim(litter_df)
```



## Arguments in 'read_csv'

```{r}
litter_df = 
  read_csv("data/FAS_litters.csv",
           skip = 5,
           col_names = FALSE,
           na = "Low8")
```


## Parsing columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```

## Reading from Excel

Read MLB data.

```{r}
mlb11 = read_excel("data/mlb11.xlsx")
```

LotR Words is next.

```{r}
fellow_df = read_excel("data/lotR_Words.xlsx",
                       range = "B3:D6")
```

## Read a SAS file

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```





















